BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS optimization_queue (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  platform TEXT NOT NULL,
  original_draft TEXT NOT NULL,
  status TEXT DEFAULT 'pending_llm',
  utm_validated INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
