#!/usr/bin/env python3
"""Helio Agent - Landing Page Specialist"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from base_agent import BaseAgent

class HelioAgent(BaseAgent):
    def generate_artifact(self, task_type: str, payload: str) -> str:
        if "hero" in payload.lower() or "branding" in payload.lower():
            return f"""<!-- VideoCourts Hero - Generated by Helio -->
<section class="hero bg-gradient-to-br from-slate-900 to-slate-800 text-white py-20">
  <div class="container mx-auto px-4 text-center">
    <h1 class="text-4xl md:text-6xl font-bold font-orbitron mb-6">⚖️ VideoCourts</h1>
    <p class="text-xl text-slate-300 mb-8 max-w-3xl mx-auto">Sovereign virtual courtroom platform powered by Constellation25 AI</p>
    <div class="flex flex-col sm:flex-row gap-4 justify-center">
      <a href="#demo" class="px-8 py-4 bg-cyan-600 hover:bg-cyan-700 rounded-lg font-semibold transition">Start Free Trial</a>
      <a href="#features" class="px-8 py-4 bg-slate-700 hover:bg-slate-600 rounded-lg font-semibold transition">View Features</a>
    </div>
  </div>
</section>
<!-- Task: {payload} -->"""
        elif "enrollment" in payload.lower() or "biometric" in payload.lower():
            return f"""<!-- Biometric Enrollment - Helio Agent -->
<section class="enrollment py-16 bg-slate-50">
  <div class="container mx-auto px-4">
    <h2 class="text-3xl font-bold text-center mb-12">Secure Biometric Enrollment</h2>
    <div class="grid md:grid-cols-3 gap-8">
      <div class="text-center p-6 bg-white rounded-xl shadow">
        <div class="text-4xl mb-4">👁️</div>
        <h3 class="font-semibold mb-2">Face Recognition</h3>
        <p class="text-slate-600 text-sm">Liveness detection + facial mapping</p>
      </div>
      <div class="text-center p-6 bg-white rounded-xl shadow">
        <div class="text-4xl mb-4">🔐</div>
        <h3 class="font-semibold mb-2">Sovereign Storage</h3>
        <p class="text-slate-600 text-sm">Encrypted, user-controlled vault</p>
      </div>
      <div class="text-center p-6 bg-white rounded-xl shadow">
        <div class="text-4xl mb-4">⚡</div>
        <h3 class="font-semibold mb-2">Instant Verification</h3>
        <p class="text-slate-600 text-sm">Sub-second authentication</p>
      </div>
    </div>
  </div>
</section>
<!-- Task: {payload} -->"""
        else:
            return f"""<!-- {task_type} - Helio Agent -->
<!-- Payload: {payload} -->
<!-- Generated: {__import__('datetime').datetime.now().isoformat()} -->
<div class="placeholder p-8 bg-slate-100 rounded text-center">
  <p class="text-slate-600">UI component placeholder for: {payload}</p>
</div>"""

if __name__ == "__main__":
    agent = HelioAgent(
        name="helio",
        tasks_dir=os.getenv("C25_TASKS", f"{os.path.expanduser('~')}/constellation25/sovereign-gtp/tasks"),
        outputs_dir=os.getenv("C25_OUTPUTS", f"{os.path.expanduser('~')}/constellation25/sovereign-gtp/outputs"),
        logs_dir=os.getenv("C25_LOGS", f"{os.path.expanduser('~')}/constellation25/sovereign-gtp/logs")
    )
    agent.run()
